# Generated by Django 6.0.3 on 2026-03-26 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deudor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='DNI/RUC')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('monto_capital', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_deuda', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cartera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_gestion', models.CharField(choices=[('SALIENTE', 'LLAMADA SALIENTE'), ('ENTRANTE', 'LLAMADA ENTRANTE'), ('CARA_A_CARA', 'ATENCIÓN CARA A CARA')], max_length=50)),
                ('tipo_contacto', models.CharField(choices=[('DIRECTO', 'CONTACTO DIRECTO'), ('INDIRECTO', 'CONTACTO INDIRECTO'), ('NO_CONTACTO', 'NO CONTACTO')], max_length=50)),
                ('resultado', models.CharField(max_length=100)),
                ('observacion', models.TextField()),
                ('fecha_promesa', models.DateField(blank=True, null=True)),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranza.deudor')),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
