# Generated by Django 6.0.3 on 2026-03-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudor',
            name='correo',
        ),
        migrations.AlterField(
            model_name='deudor',
            name='documento',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='nombre_completo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='resultado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='tipo_contacto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='tipo_gestion',
            field=models.CharField(max_length=50),
        ),
    ]
