# Generated by Django 6.0.3 on 2026-03-26 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0002_remove_deudor_correo_alter_deudor_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deudor',
            old_name='telefono',
            new_name='telefono_principal',
        ),
        migrations.CreateModel(
            name='TelefonoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('descripcion', models.CharField(default='Adicional', max_length=50)),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='cobranza.deudor')),
            ],
        ),
    ]
