# Generated by Django 6.0.3 on 2026-03-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0003_rename_telefono_deudor_telefono_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='tipo_contacto',
        ),
        migrations.AddField(
            model_name='deudor',
            name='agencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='cuenta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
