# Generated by Django 6.0.3 on 2026-03-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0004_remove_gestion_tipo_contacto_deudor_agencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='monto_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='tipo_gestion',
            field=models.CharField(default='LLAMADA', max_length=50),
        ),
    ]
