# Generated by Django 6.0.3 on 2026-03-27 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0005_gestion_fecha_pago_gestion_monto_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='gestion',
            name='tipo_gestion',
        ),
        migrations.AddField(
            model_name='deudor',
            name='dir_casa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='nom_aval',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='nom_conyuge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='nom_conyuge_aval',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='rango_dias_mora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='tlf_celular_aval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='agencia',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='cartera',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='cuenta',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='monto_capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='saldo_deuda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='telefono_principal',
            field=models.CharField(default='Sin número', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gestion',
            name='gestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='monto_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='resultado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='telefonoextra',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='telefonoextra',
            name='deudor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranza.deudor'),
        ),
    ]
