# Generated by Django 6.0.3 on 2026-03-31 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0006_remove_gestion_fecha_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartera_nombre', models.CharField(max_length=100)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteras_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('gestor', 'cartera_nombre')},
            },
        ),
    ]
