# Generated by Django 6.0.3 on 2026-04-01 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0007_asignacioncartera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacioncartera',
            old_name='cartera_nombre',
            new_name='valor',
        ),
        migrations.AlterUniqueTogether(
            name='asignacioncartera',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asignacioncartera',
            name='tipo',
            field=models.CharField(choices=[('cartera', 'Cartera'), ('agencia', 'Agencia')], default='cartera', max_length=10),
        ),
        migrations.AlterField(
            model_name='asignacioncartera',
            name='gestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='asignacioncartera',
            unique_together={('gestor', 'tipo', 'valor')},
        ),
    ]
