# Generated by Django 6.0.3 on 2026-04-11 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0008_rename_cartera_nombre_asignacioncartera_valor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaAsterisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Campaña')),
                ('proveedor', models.CharField(choices=[('CAJA HUANCAYO', 'Caja Huancayo'), ('PROEMPRESA', 'Proempresa'), ('FOCMAC', 'Focmac')], max_length=50, verbose_name='Proveedor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Campaña Activa?')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Campaña Asterisk',
                'verbose_name_plural': 'Campañas Asterisk',
                'ordering': ['-id'],
            },
        ),
    ]
