# Generated by Django 6.0.3 on 2026-04-11 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0009_campanaasterisk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCampanaAsterisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('cod_cliente', models.CharField(max_length=100, verbose_name='Código Cliente (Kubo)')),
                ('cod_telefono', models.CharField(max_length=100, verbose_name='Código Teléfono (Kubo)')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cobranza.campanaasterisk')),
            ],
            options={
                'verbose_name': 'Detalle de Campaña',
                'verbose_name_plural': 'Detalles de Campaña',
            },
        ),
    ]
