# Generated by Django 6.0.3 on 2026-04-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0011_deudor_ultimo_dia_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudor',
            name='aval_direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='aval_distrito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='codigo_cautelar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='condicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='detalle_bien',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='estado_medida_cautelar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='estado_proceso_principal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='expediente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='fec_demanda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='foto_evidencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='gestion_extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='ingreso_judicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='juzgado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='link_gps',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='link_gps_aval',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='monto_demanda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='proceso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='referencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='seguimiento_cautelar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='seguimiento_principal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
