# Generated by Django 6.0.3 on 2026-04-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0012_deudor_campos_app_movil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudor',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/'),
        ),
    ]
