# Generated by Django 6.0.3 on 2026-04-27 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0015_deudor_campos_campo_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteSIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.CharField(max_length=20, verbose_name='Anexo SIP')),
                ('clave', models.CharField(max_length=200, verbose_name='Clave Secreta SIP')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sip_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil SIP de Agente',
                'verbose_name_plural': 'Perfiles SIP de Agentes',
            },
        ),
    ]
