# Generated by Django 6.0.3 on 2026-05-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0017_asignaciondiaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudor',
            name='negociacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
