# Generated by Django 6.0.3 on 2026-05-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0018_deudor_negociacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='hora_promesa',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguimientoprogramado',
            name='hora_programada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Programada'),
        ),
    ]
