# Generated by Django 6.0.3 on 2026-06-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0019_gestion_hora_promesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudor',
            name='documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='deudor',
            unique_together={('documento', 'cuenta')},
        ),
    ]
