# Generated by Django 6.0.3 on 2026-07-15 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0020_alter_deudor_documento_alter_deudor_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('cuota_pendiente', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('monto_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dias_atraso', models.IntegerField(default=0)),
                ('situacion', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='cobranza.deudor')),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
            },
        ),
    ]
