# Generated by Django 6.0.3 on 2026-07-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0021_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
