# Generated by Django 6.0.3 on 2026-07-22 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0022_deudor_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Pagado')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago (según cliente)')),
                ('imagen', models.ImageField(upload_to='vouchers/', verbose_name='Foto del Voucher')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='cobranza.deudor')),
            ],
            options={
                'verbose_name': 'Voucher de Pago',
                'verbose_name_plural': 'Vouchers de Pago',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
