# Generated by Django 6.0.3 on 2026-08-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0023_voucherpago'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudor',
            name='correlativo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
