# Generated by Django 6.0.3 on 2026-08-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0024_deudor_correlativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentesip',
            name='score',
            field=models.IntegerField(default=10, help_text='Puntaje AI de Probabilidad de Pago'),
        ),
        migrations.AddField(
            model_name='asignacioncartera',
            name='score',
            field=models.IntegerField(default=10, help_text='Puntaje AI de Probabilidad de Pago'),
        ),
        migrations.AddField(
            model_name='asignaciondiaria',
            name='score',
            field=models.IntegerField(default=10, help_text='Puntaje AI de Probabilidad de Pago'),
        ),
        migrations.AddField(
            model_name='campanaasterisk',
            name='score',
            field=models.IntegerField(default=10, help_text='Puntaje AI de Probabilidad de Pago'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='score',
            field=models.IntegerField(default=10, help_text='Puntaje AI de Probabilidad de Pago'),
        ),
        migrations.AddField(
            model_name='detallecampanaasterisk',
            name='score',
            field=models.IntegerField(default=10, help_text='Puntaje AI de Probabilidad de Pago'),
        ),
        migrations.AddField(
            model_name='deudor',
            name='score',
            field=models.IntegerField(default=10, help_text='Puntaje AI de Probabilidad de Pago'),
        ),
        migrations.AddField(
            model_name='seguimientoprogramado',
            name='score',
            field=models.IntegerField(default=10, help_text='Puntaje AI de Probabilidad de Pago'),
        ),
        migrations.AddField(
            model_name='voucherpago',
            name='score',
            field=models.IntegerField(default=10, help_text='Puntaje AI de Probabilidad de Pago'),
        ),
    ]
