# Generated by Django 6.0.3 on 2026-08-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0025_agentesip_score_asignacioncartera_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentesip',
            name='score',
        ),
        migrations.RemoveField(
            model_name='asignacioncartera',
            name='score',
        ),
        migrations.RemoveField(
            model_name='asignaciondiaria',
            name='score',
        ),
        migrations.RemoveField(
            model_name='campanaasterisk',
            name='score',
        ),
        migrations.RemoveField(
            model_name='convenio',
            name='score',
        ),
        migrations.RemoveField(
            model_name='detallecampanaasterisk',
            name='score',
        ),
        migrations.RemoveField(
            model_name='seguimientoprogramado',
            name='score',
        ),
        migrations.RemoveField(
            model_name='voucherpago',
            name='score',
        ),
    ]
