# Generated by Django 6.0.3 on 2026-09-01 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0026_remove_agentesip_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActoProcesal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_resolucion', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de Resolución')),
                ('fecha_resolucion', models.DateField(verbose_name='Fecha de Resolución')),
                ('fecha_notificacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Notificación')),
                ('descripcion', models.TextField(verbose_name='Descripción / Resumen')),
                ('fojas', models.IntegerField(blank=True, null=True, verbose_name='Fojas')),
                ('sumilla', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sumilla')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acto Procesal',
                'verbose_name_plural': 'Actos Procesales',
                'ordering': ['-fecha_resolucion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(max_length=100, verbose_name='N° de Expediente Principal')),
                ('numero_cautelar', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de Expediente Cautelar')),
                ('materia', models.CharField(max_length=150, verbose_name='Materia del Proceso')),
                ('juzgado', models.CharField(max_length=200, verbose_name='Juzgado')),
                ('especialista_legal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialista Legal')),
                ('estado_proceso', models.CharField(choices=[('ACTIVO', 'Activo'), ('ARCHIVO', 'Archivo Provisional'), ('CONCLUIDO', 'Concluido')], default='ACTIVO', max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio del Proceso')),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes_judiciales', to='cobranza.deudor')),
            ],
            options={
                'verbose_name': 'Expediente Judicial',
                'verbose_name_plural': 'Expedientes Judiciales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AlertaJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(max_length=150, verbose_name='Tipo de Alerta / Tarea')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('acto_procesal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cobranza.actoprocesal')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cobranza.expedientejudicial')),
            ],
            options={
                'verbose_name': 'Alerta Judicial',
                'verbose_name_plural': 'Alertas Judiciales',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.AddField(
            model_name='actoprocesal',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actos_procesales', to='cobranza.expedientejudicial'),
        ),
    ]
