# Generated by Django 6.0.3 on 2026-09-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0027_actoprocesal_expedientejudicial_alertajudicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actoprocesal',
            name='cuaderno',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('CAUTELAR', 'Cautelar')], default='PRINCIPAL', max_length=20),
        ),
        migrations.AddField(
            model_name='expedientejudicial',
            name='codigo_cautelar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Cautelar'),
        ),
        migrations.AddField(
            model_name='expedientejudicial',
            name='condicion_recuperabilidad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Condición'),
        ),
        migrations.AddField(
            model_name='expedientejudicial',
            name='detalle_bien',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle del Bien / Garantía'),
        ),
        migrations.AddField(
            model_name='expedientejudicial',
            name='distrito_judicial',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Distrito Judicial'),
        ),
        migrations.AddField(
            model_name='expedientejudicial',
            name='estado_cautelar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Medida Cautelar'),
        ),
        migrations.AddField(
            model_name='expedientejudicial',
            name='fecha_cautelar',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Presentación Cautelar'),
        ),
        migrations.AddField(
            model_name='expedientejudicial',
            name='monto_demandado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Demandado'),
        ),
        migrations.AddField(
            model_name='expedientejudicial',
            name='probabilidad_recuperacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Probabilidad de Recuperación'),
        ),
        migrations.AddField(
            model_name='expedientejudicial',
            name='sede_judicial',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Sede Judicial'),
        ),
        migrations.AddField(
            model_name='expedientejudicial',
            name='tipo_medida_cautelar',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo Medida Cautelar'),
        ),
    ]
