# Generated by Django 6.0.3 on 2026-09-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0028_actoprocesal_cuaderno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudor',
            name='credito_al_dia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='cuota_pendiente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='dias_atraso_cuota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='fecha_pago_cuota_pendiente',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='monto_cuota_atrasada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deudor',
            name='total_cuotas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
