"""
Django settings for crm_pyp_config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ══════════════════════════════════════════════════════════════════════════════
# JAZZMIN — Tema visual del panel administrativo
# ══════════════════════════════════════════════════════════════════════════════
JAZZMIN_SETTINGS = {
    # ── Identidad ─────────────────────────────────────────────────────────────
    "site_title":        "CRM P&P",
    "site_header":       "P&P Soluciones Jurídicas",
    "site_brand":        "P&P Cobranza",
    "welcome_sign":      "Bienvenido al Panel Administrativo",
    "copyright":         "P&P Soluciones Jurídicas © 2026",

    # ── Iconos por modelo (FontAwesome 5) ─────────────────────────────────────
    "icons": {
        "auth":                          "fas fa-users-cog",
        "auth.user":                     "fas fa-user",
        "auth.group":                    "fas fa-users",
        "cobranza.deudor":               "fas fa-file-invoice-dollar",
        "cobranza.gestion":              "fas fa-clipboard-list",
        "cobranza.telefonoextra":        "fas fa-phone-alt",
        "cobranza.asignacioncartera":    "fas fa-briefcase",
        "cobranza.campanaasterisk":      "fas fa-bullhorn",
        "cobranza.detallecampanaasterisk": "fas fa-list-ol",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    # ── Menú lateral organizado por secciones ─────────────────────────────────
    "order_with_respect_to": [
        "cobranza.deudor",
        "cobranza.gestion",
        "cobranza.telefonoextra",
        "cobranza.asignacioncartera",
        "cobranza.campanaasterisk",
        "cobranza.detallecampanaasterisk",
        "auth",
    ],

    # ── Interfaz ──────────────────────────────────────────────────────────────
    "show_ui_builder":          False,
    "navigation_expanded":      True,
    "hide_apps":                [],
    "hide_models":              [],
    "related_modal_active":     True,
    "custom_css":               None,
    "custom_js":                None,
    "use_google_fonts_cdn":     False,
    "show_sidebar":             True,
    "topmenu_links": [
        {"name": "Inicio CRM",  "url": "/dashboard/",       "new_window": False},
        {"name": "Bandeja",     "url": "/bandeja-gestor/",  "new_window": False},
        {"name": "Campañas",    "url": "/campanas-asterisk/", "new_window": False},
    ],
    "usermenu_links": [
        {"name": "Ir al CRM",   "url": "/dashboard/",       "new_window": False},
    ],
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    # ── Tema Bootstrap base ───────────────────────────────────────────────────
    "navbar_small_text":    False,
    "footer_small_text":    False,
    "body_small_text":      False,
    "brand_small_text":     False,

    # ── Colores: azul marino + blanco (marca P&P) ─────────────────────────────
    "brand_colour":         "navbar-dark",
    "accent":               "accent-warning",       # dorado ámbar en links activos
    "navbar":               "navbar-dark",
    "no_navbar_border":     True,
    "navbar_fixed":         True,
    "layout_boxed":         False,
    "footer_fixed":         False,
    "sidebar_fixed":        True,
    "sidebar":              "sidebar-dark-primary",  # sidebar oscuro azul
    "sidebar_nav_small_text":       False,
    "sidebar_disable_expand":       False,
    "sidebar_nav_child_indent":     True,
    "sidebar_nav_compact_style":    False,
    "sidebar_nav_legacy_style":     False,
    "sidebar_nav_flat_style":       False,
    "theme":                "default",
    "dark_mode_theme":      None,
    "button_classes": {
        "primary":   "btn-primary",
        "secondary": "btn-warning",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },
}

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7%s0wl=)k%v8=z-6n(7f!vwn5$hhc)4kqfc5nl-uh0f7u)k1ru'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.43', '127.0.0.1', 'localhost', '134.209.76.91', 'crm.pypsolucionesjuridicas.com']


# Application definition

INSTALLED_APPS = [
    'jazzmin',                      # ← debe ir ANTES de django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # AGREGAR ESTA LÍNEA
    'cobranza',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crm_pyp_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm_pyp_config.wsgi.application'


import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'pyp_db',                  # <--- Aquí confirmas el nombre
        'USER': 'postgres',                # <--- El usuario
        'PASSWORD': 'Moises16Micaela12pyp', # <--- Tu contraseña actual
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/' # Al salir, regresamos al inicio

ZADARMA_KEY = '9eaec4a0660c4158c877'
ZADARMA_SECRET = 'f6735045cdda663f6f51'
ZADARMA_SIP = '398200-100'  # Tu ID de agente
API_TOKEN_ZADARMA = 'pyp-webrtc-2026-secure-token-key'  # Token para widget

# Ruta al archivo llave.json de la Service Account de Google (para app móvil)
# Coloca el archivo en la raíz del proyecto con el nombre llave.json
LLAVE_JSON_PATH = BASE_DIR / 'llave.json'